server:
  port: 8081
  servlet:
    context-path: /
  connection-timeout: 18000000
  tomcat:
    max-http-post-size: 104857600
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mwd?useUnicode=true&amp;amp;characterEncoding=UTF-8&amp;amp;autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cache:
    redis:
      time-to-live: -1
  mail:
    host: smtp.qq.com
    port: 587
    username: 2925904594@qq.com
    password: zemljfesefwyddfh
    protocol: smtp
    default-encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1024MB
      max-request-size: 1024MB
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zzd.api.dao

constants:
  coverBaseUrl: D:/Program Files/fileDepository/
  mediaBaseUrl: D:/Program Files/fileDepository/
  newsBaseUrl: D:/Program Files/fileDepository/


